### ISSUE TITLE
Tuning Phase

### ISSUE THREAD

**Issue by Data-Designer** [haihuangcode/CMG#15]
这个任务在第一阶段进行pretrain,第二阶段不是该frozen Encoder参数吗？我看tuning的时候似乎Encoder会一起更新？

**Comment by haihuangcode** [comment]
在tuning过程中，由于调用encoder时前面加了with torch.no_grad()，所以即使在optimizer中将encoder的参数包含进去，它的参数也不会被更新。实际测试中，只使用下游decoder的参数作为optimizer，结果也是一样的。不过您提到的确实是多余的部分，非常感谢您的指出，我会针对这个问题进行修改。
